#!/usr/bin/env bash
ip addr show dev eth0 | sed -e's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d' | sed -n 1p

# Check if command is available
is_command() {
    # Checks to see if the given command (passed as a string argument) exists on the system.
    # The function returns 0 (success) if the command exists, and 1 if it doesn't.
    local check_command="$1"

    command -v "${check_command}" >/dev/null 2>&1
}

# Cronjob
install_cronjob() {
  # install_cronjob "script.sh" "* * * * 6"
  command=$1
  interval=$2
  job="$interval $command"
  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
}

is_root() {
    # If the user's id is zero,
    if [[ "${EUID}" -eq 0 ]]; then
       return 1
    else
        return 0
 fi
}

if is_root -eq 0; then
    echo "No Root"
else
    echo "Root"
fi

if is_command apt-get ; then
  echo "We are on Debian"
  apt-get install mc
  apt-get install htop
fi



echo "Done."
